# Generated by Django 5.2 on 2025-05-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='musician_profiles',
            field=models.ManyToManyField(to='band.musician'),
        ),
    ]
