# Generated by Django 5.2 on 2025-05-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0005_userprofile_musician_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='venue_controlled',
            field=models.ManyToManyField(to='band.venue'),
        ),
    ]
