# Generated by Django 5.0.6 on 2025-06-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_alter_userprofile_venue_controlled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='musician_profiles',
            field=models.ManyToManyField(blank=True, to='band.musician'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='venue_controlled',
            field=models.ManyToManyField(blank=True, to='band.venue'),
        ),
    ]
